In [6]:
import pandas as pd

In [7]:
csv_path = "Resources/summer.csv"

In [8]:
amjad_df=pd.read_csv(csv_path)

In [9]:
amjad_df

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
31160,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
31161,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
31162,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
31163,2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
31164,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

In [31]:
host_df=amjad_df.groupby('City')["Year"].unique()
host_df

City
Amsterdam                            [1928]
Antwerp                              [1920]
Athens                         [1896, 2004]
Atlanta                              [1996]
Barcelona                            [1992]
Beijing                              [2008]
Berlin                               [1936]
Helsinki                             [1952]
London                   [1908, 1948, 2012]
Los Angeles                    [1932, 1984]
Melbourne / Stockholm                [1956]
Mexico                               [1968]
Montreal                             [1976]
Moscow                               [1980]
Munich                               [1972]
Paris                          [1900, 1924]
Rome                                 [1960]
Seoul                                [1988]
St Louis                             [1904]
Stockholm                            [1912]
Sydney                               [2000]
Tokyo                                [1964]
Name: Year, dtype: object

In [37]:
gbr_df=amjad_df.loc[(amjad_df["Country"] == "GBR") & ( (amjad_df["Year"] == 1896) | (amjad_df["Year"] == 1900) | (amjad_df["Year"] == 1904) )]
gbr_df

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
16,1896,Athens,Athletics,Athletics,"GOULDING, Grantley",GBR,Men,110M Hurdles,Silver
20,1896,Athens,Athletics,Athletics,"GMELIN, Charles",GBR,Men,400M,Bronze
48,1896,Athens,Cycling,Cycling Road,"BATTEL, Edward",GBR,Men,Individual Road Race,Bronze
57,1896,Athens,Cycling,Cycling Track,"KEEPING, Frank",GBR,Men,12-Hour Race,Silver
140,1896,Athens,Tennis,Tennis,"BOLAND, John",GBR,Men,Singles,Gold
...,...,...,...,...,...,...,...,...,...
645,1900,Paris,Tennis,Tennis,"DOHERTY, Hugh Lawrence",GBR,Men,Singles,Gold
646,1900,Paris,Tennis,Tennis,"MAHONY, Harold Sergerson",GBR,Men,Singles,Silver
649,1900,Paris,Tennis,Tennis,"COOPER, Charlotte",GBR,Women,Singles,Gold
753,1904,St Louis,Athletics,Athletics,"DALY, John",GBR,Men,3000M Steeplechase,Silver
780,1904,St Louis,Athletics,Athletics,"KIELY, Thomas Francis",GBR,Men,Decathlon,Gold

In [36]:
athens_df=amjad_df.loc[(amjad_df["Country"] == "GRE") & ( (amjad_df["Year"] == 1896) | (amjad_df["Year"] == 1900) | (amjad_df["Year"] == 1904) )]
athens_df

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver
5,1896,Athens,Aquatics,Swimming,"CHOROPHAS, Efstathios",GRE,Men,1200M Freestyle,Bronze
7,1896,Athens,Aquatics,Swimming,"ANDREOU, Joannis",GRE,Men,1200M Freestyle,Silver
8,1896,Athens,Aquatics,Swimming,"CHOROPHAS, Efstathios",GRE,Men,400M Freestyle,Bronze
10,1896,Athens,Aquatics,Swimming,"PEPANOS, Antonios",GRE,Men,400M Freestyle,Silver
23,1896,Athens,Athletics,Athletics,"GOLEMIS, Dimitrios",GRE,Men,800M,Bronze
26,1896,Athens,Athletics,Athletics,"VERSIS, Sotirios",GRE,Men,Discus Throw,Bronze
28,1896,Athens,Athletics,Athletics,"PARASKEVOPOULOS, Panagiotis",GRE,Men,Discus Throw,Silver
36,1896,Athens,Athletics,Athletics,"LOUIS, Spyridon",GRE,Men,Marathon,Gold
37,1896,Athens,Athletics,Athletics,"VASILAKOS, Kharilaos",GRE,Men,Marathon,Silver
38,1896,Athens,Athletics,Athletics,"DAMASKOS, Evangelos",GRE,Men,Pole Vault,Bronze
39,1896,Athens,Athletics,Athletics,"THEODOROPOULOS, Ioannis",GRE,Men,Pole Vault,Bronze
42,1896,Athens,Athletics,Athletics,"PAPASIDERIS, Georgios",GRE,Men,Shot Put,Bronze
44,1896,Athens,Athletics,Athletics,"GOUSKOS, Miltiadis",GRE,Men,Shot Put,Silver
45,1896,Athens,Athletics,Athletics,"PERSAKIS, Ioannis",GRE,Men,Triple Jump,Bronze
49,1896,Athens,Cycling,Cycling Road,"KONSTANTINIDIS, Aristidis",GRE,Men,Individual Road Race,Gold
52,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100KM,Silver
60,1896,Athens,Cycling,Cycling Track,"NIKOLOPOULOS, Stamatios",GRE,Men,1KM Time Trial,Silver
63,1896,Athens,Cycling,Cycling Track,"NIKOLOPOULOS, Stamatios",GRE,Men,Sprint Indivual,Silver
64,1896,Athens,Fencing,Fencing,"PIERRAKOS-MAVROMICHALIS, Perikles",GRE,Men,Foil Individual,Bronze
67,1896,Athens,Fencing,Fencing,"PYRGOS, Leonidas",GRE,Men,"Foil, Masters",Gold
70,1896,Athens,Fencing,Fencing,"GEORGIADIS, Ioannis",GRE,Men,Sabre Individual,Gold
71,1896,Athens,Fencing,Fencing,"KARAKALOS, Telemachos",GRE,Men,Sabre Individual,Silver
78,1896,Athens,Gymnastics,Artistic G.,"PERSAKIS, Petros",GRE,Men,Rings,Bronze
79,1896,Athens,Gymnastics,Artistic G.,"MITROPOULOS, Ioannis",GRE,Men,Rings,Gold
82,1896,Athens,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,Rope Climbing,Gold
83,1896,Athens,Gymnastics,Artistic G.,"XENAKIS, Thomasios",GRE,Men,Rope Climbing,Silver
95,1896,Athens,Gymnastics,Artistic G.,"CHRYSAPHIS, Ioannis",GRE,Men,"Team, Parallel Bars",Bronze
96,1896,Athens,Gymnastics,Artistic G.,"KARVELAS, Phillippos",GRE,Men,"Team, Parallel Bars",Bronze
97,1896,Athens,Gymnastics,Artistic G.,"LOUNDRAS, Dimitrios",GRE,Men,"Team, Parallel Bars",Bronze
98,1896,Athens,Gymnastics,Artistic G.,"MITROPOULOS, Ioannis",GRE,Men,"Team, Parallel Bars",Bronze
110,1896,Athens,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,"Team, Parallel Bars",Silver
111,1896,Athens,Gymnastics,Artistic G.,"ATHANASOPOULOS, Spyros",GRE,Men,"Team, Parallel Bars",Silver
112,1896,Athens,Gymnastics,Artistic G.,"PERSAKIS, Petros",GRE,Men,"Team, Parallel Bars",Silver
113,1896,Athens,Gymnastics,Artistic G.,"XENAKIS, Thomasios",GRE,Men,"Team, Parallel Bars",Silver
117,1896,Athens,Shooting,Shooting,"MORAKIS, Nikolaos",GRE,Men,25M Army Pistol,Bronze
121,1896,Athens,Shooting,Shooting,"PHRANGOUDIS, Joannis",GRE,Men,25M Rapid Fire Pistol (60 Shots),Gold
122,1896,Athens,Shooting,Shooting,"ORPHANIDIS, Georgios",GRE,Men,25M Rapid Fire Pistol (60 Shots),Silver
123,1896,Athens,Shooting,Shooting,"PHRANGOUDIS, Joannis",GRE,Men,50M Pistol (60 Shots),Bronze
126,1896,Athens,Shooting,Shooting,"TRIKUPIS, Nicolaos",GRE,Men,"Army Rifle, 200M",Bronze
127,1896,Athens,Shooting,Shooting,"KARASEVDAS, Pantelis",GRE,Men,"Army Rifle, 200M",Gold
128,1896,Athens,Shooting,Shooting,"PAVLIDIS, Pavlos",GRE,Men,"Army Rifle, 200M",Silver
130,1896,Athens,Shooting,Shooting,"ORPHANIDIS, Georgios",GRE,Men,"Army Rifle, 300M",Gold
131,1896,Athens,Shooting,Shooting,"PHRANGOUDIS, Joannis",GRE,Men,"Army Rifle, 300M",Silver
138,1896,Athens,Tennis,Tennis,"PASPATIS, Konstantinos",GRE,Men,Singles,Bronze
141,1896,Athens,Tennis,Tennis,"KASDAGLIS, Dionysios",GRE,Men,Singles,Silver
142,1896,Athens,Weightlifting,Weightlifting,"NIKOLOPOULOS, Alexandros",GRE,Men,Heavyweight - One Hand Lift,Bronze
145,1896,Athens,Weightlifting,Weightlifting,"VERSIS, Sotirios",GRE,Men,Heavyweight - Two Hand Lift,Bronze
148,1896,Athens,Wrestling,Wrestling Gre-R,"CHRISTOPOULOS, Stephanos",GRE,Men,Open Event,Bronze
150,1896,Athens,Wrestling,Wrestling Gre-R,"TSITAS, Georgios",GRE,Men,Open Event,Silver
782,1904,St Louis,Athletics,Athletics,"GEORGANDAS, Nicolaos",GRE,Men,Discus Throw,Bronze
1110,1904,St Louis,Weightlifting,Weightlifting,"KAKOUSIS, Perikles",GRE,Men,Heavyweight - Two Hand Lift,Gold